spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5

  datasource:
    url: jdbc:h2:mem:hwoolog
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true
    generate-ddl: true

  sql:
    init:
      mode: always
